version: "3"

tasks:
  genMetrics:
    aliases:
      - genMetrics
    desc: "Generate code for \"metrics\" project from proto files"
    cmds:
      - protoc -I proto proto/metrics/metrics.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative

